ACLOCAL_AMFLAGS = -I m4

common_sources  = BasicHashtable.cpp
#common_sources += CallStack.cpp
common_sources += FileMap.cpp
common_sources += JenkinsHash.cpp
common_sources += LinearTransform.cpp
common_sources += Log.cpp
common_sources += NativeHandle.cpp
common_sources += Printer.cpp
#common_sources += ProcessCallStack.cpp
common_sources += PropertyMap.cpp
common_sources += RefBase.cpp
common_sources += SharedBuffer.cpp
common_sources += Static.cpp
common_sources += StopWatch.cpp
common_sources += String8.cpp
common_sources += String16.cpp
common_sources += SystemClock.cpp
common_sources += Threads.cpp
common_sources += Timers.cpp
common_sources += Tokenizer.cpp
common_sources += Unicode.cpp
common_sources += VectorImpl.cpp
common_sources += misc.cpp

# Build libutils.so
lib_LTLIBRARIES       = libutils.la
libutils_la_SOURCES   = $(common_sources)
libutils_la_CPPFLAGS  = -I$(srcdir)/../include/
#libutils_la_CPPFLAGS += -I$(top_srcdir)/liblog
libutils_la_CPPFLAGS += -DHAVE_PTHREADS
libutils_la_CPPFLAGS += -DLINUX_ENABLED
libutils_la_CPPFLAGS += -D__linux__
libutils_la_CPPFLAGS += -DANDROID_SMP=0
libutils_la_CPPFLAGS += -DDEBUG_REFS_CALLSTACK_ENABLED=0
libutils_la_CPPFLAGS += -std=c++14 -std=gnu++14 -fpermissive

requiredlibs = -lpthread

# Export headers
incdir = $(srcdir)/../include
utilsincdir       = $(includedir)/utils
utilsinc_HEADERS  = $(incdir)/utils/AndroidThreads.h
utilsinc_HEADERS += $(incdir)/utils/ashmem.h
utilsinc_HEADERS += $(incdir)/utils/Atomic.h
utilsinc_HEADERS += $(incdir)/utils/BasicHashtable.h
utilsinc_HEADERS += $(incdir)/utils/BitSet.h
utilsinc_HEADERS += $(incdir)/utils/BlobCache.h
utilsinc_HEADERS += $(incdir)/utils/ByteOrder.h
utilsinc_HEADERS += $(incdir)/utils/CallStack.h
utilsinc_HEADERS += $(incdir)/utils/Compat.h
utilsinc_HEADERS += $(incdir)/utils/Condition.h
utilsinc_HEADERS += $(incdir)/utils/Debug.h
utilsinc_HEADERS += $(incdir)/utils/Endian.h
utilsinc_HEADERS += $(incdir)/utils/Errors.h
utilsinc_HEADERS += $(incdir)/utils/FileMap.h
utilsinc_HEADERS += $(incdir)/utils/Flattenable.h
utilsinc_HEADERS += $(incdir)/utils/Functor.h
utilsinc_HEADERS += $(incdir)/utils/JenkinsHash.h
utilsinc_HEADERS += $(incdir)/utils/KeyedVector.h
utilsinc_HEADERS += $(incdir)/utils/LinearTransform.h
utilsinc_HEADERS += $(incdir)/utils/List.h
utilsinc_HEADERS += $(incdir)/utils/Log.h
utilsinc_HEADERS += $(incdir)/utils/Looper.h
utilsinc_HEADERS += $(incdir)/utils/LruCache.h
utilsinc_HEADERS += $(incdir)/utils/misc.h
utilsinc_HEADERS += $(incdir)/utils/Mutex.h
utilsinc_HEADERS += $(incdir)/utils/NativeHandle.h
utilsinc_HEADERS += $(incdir)/utils/Printer.h
#utilsinc_HEADERS += $(incdir)/utils/ProcessCallStack.h
utilsinc_HEADERS += $(incdir)/utils/PropertyMap.h
utilsinc_HEADERS += $(incdir)/utils/RefBase.h
utilsinc_HEADERS += $(incdir)/utils/RWLock.h
utilsinc_HEADERS += $(incdir)/utils/SharedBuffer.h
utilsinc_HEADERS += $(incdir)/utils/Singleton.h
utilsinc_HEADERS += $(incdir)/utils/SortedVector.h
utilsinc_HEADERS += $(incdir)/utils/StopWatch.h
utilsinc_HEADERS += $(incdir)/utils/String16.h
utilsinc_HEADERS += $(incdir)/utils/String8.h
utilsinc_HEADERS += $(incdir)/utils/StrongPointer.h
utilsinc_HEADERS += $(incdir)/utils/SystemClock.h
utilsinc_HEADERS += $(incdir)/utils/ThreadDefs.h
utilsinc_HEADERS += $(incdir)/utils/Thread.h
utilsinc_HEADERS += $(incdir)/utils/threads.h
utilsinc_HEADERS += $(incdir)/utils/Timers.h
utilsinc_HEADERS += $(incdir)/utils/Tokenizer.h
utilsinc_HEADERS += $(incdir)/utils/Trace.h
utilsinc_HEADERS += $(incdir)/utils/TypeHelpers.h
utilsinc_HEADERS += $(incdir)/utils/Unicode.h
utilsinc_HEADERS += $(incdir)/utils/Vector.h
utilsinc_HEADERS += $(incdir)/utils/VectorImpl.h

pkgconfigdir    = $(libdir)/pkgconfig
pkgconfig_DATA  = libutils.pc
EXTRA_DIST      = $(pkgconfig_DATA)
